import Header from './components/Header'
import './globals.css'


export const metadata = {
  title: 'Kina Digital Studio Media',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <main className='container'>{children}</main>
      </body>
    </html>
  )
}
